---
name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  static-checks:
    name: Static checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.4.0
        with:
          python-version: 3.9
      - uses: Scony/godot-gdscript-toolkit@4.2.2
        with:
          version: 3.5.0
      - run: gdformat --check scenes/
      - run: gdlint scenes/
      - run: gdformat --check scripts/
      - run: gdlint scripts/
